# -*- coding: utf-8 -*-
"""Catálogo curado de ejercicios con GIFs de demostración.

Fuente: https://github.com/hasaneyldrm/exercises-dataset (media © Gym Visual, usado con permiso).
Instrucciones en español. GIFs servidos desde raw.githubusercontent.com.
"""

EXERCISES = [
    {
        'name': 'barbell bench press',
        'category': 'chest',
        'body_part': 'chest',
        'equipment': 'barbell',
        'muscle_group': 'triceps',
        'target': 'pectorals',
        'secondary_muscles': 'triceps, shoulders',
        'difficulty': 'beginner',
        'instructions': 'Túmbate sobre un banco con los pies apoyados en el suelo y la espalda presionada contra el banco. Agarra la barra con un agarre pronado un poco más ancho que la separación de los hombros. Levanta la barra del soporte y sostenla directamente sobre el pecho con los brazos completamente extendidos. Baja la barra lentamente hacia el pecho, manteniendo los codos pegados al cuerpo. Haz una pausa breve cuando la barra toque el pecho. Empuja la barra de vuelta a la posición inicial extendiendo los brazos. Repite el número de repeticiones deseado.',
        'tips': 'Mantén los pies firmes en el suelo durante todo el movimiento. Activa el core para estabilizar el tronco. Baja la barra hasta el pecho medio, por debajo de los pezones. Controla la bajada (2-3 segundos) y sube con potencia (1 segundo).',
        'common_mistakes': 'No arquees excesivamente la espalda baja. No reboten la barra sobre el pecho. No extiendas los codos al bloquear arriba. No levantes los glúteos del banco.',
        'modifications': 'Si tienes problemas de humbros, usa mancuernas en lugar de barra. Para principiantes, empieza con la barra vacía (20kg) hasta dominar la técnica.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0025-EIeI8Vf.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0025-EIeI8Vf.jpg',
    },
    {
        'name': 'dumbbell incline bench press',
        'category': 'chest',
        'body_part': 'chest',
        'equipment': 'dumbbell',
        'muscle_group': 'shoulders',
        'target': 'pectorals',
        'secondary_muscles': 'shoulders, triceps',
        'difficulty': 'beginner',
        'instructions': 'Coloca un banco inclinado a un ángulo de 45 grados. Siéntate en el banco con los pies apoyados en el suelo y la espalda firmemente apoyada contra el banco. Sostén una mancuerna en cada mano, con las palmas hacia adelante, y levántalas hasta la altura de los hombros. Baja lentamente las mancuernas hacia los lados del pecho, manteniendo los codos en un ángulo de 90 grados. Empuja las mancuernas de nuevo hacia arriba hasta la posición inicial, extendiendo completamente los brazos. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0314-ns0SIbU.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0314-ns0SIbU.jpg',
    },
    {
        'name': 'push-up',
        'category': 'chest',
        'body_part': 'chest',
        'equipment': 'body weight',
        'muscle_group': 'triceps',
        'target': 'pectorals',
        'secondary_muscles': 'triceps, deltoids, core',
        'difficulty': 'beginner',
        'instructions': 'Comienza en una posición de plancha alta con las manos un poco más separadas que la anchura de los hombros y los pies juntos. Activa el core y baja el cuerpo hacia el suelo flexionando los codos, manteniendo el cuerpo en línea recta. Haz una pausa cuando el pecho esté justo por encima del suelo y luego empújate de vuelta a la posición inicial estirando los brazos. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0662-I4hDWkc.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0662-I4hDWkc.jpg',
    },
    {
        'name': 'dumbbell fly',
        'category': 'chest',
        'body_part': 'chest',
        'equipment': 'dumbbell',
        'muscle_group': 'shoulders',
        'target': 'pectorals',
        'secondary_muscles': 'shoulders',
        'difficulty': 'beginner',
        'instructions': 'Túmbate boca arriba en un banco con una mancuerna en cada mano, con las palmas enfrentadas entre sí. Extiende los brazos rectos hacia arriba sobre el pecho, con una ligera flexión en los codos. Manteniendo una ligera flexión en los codos, baja los brazos hacia los lados en un amplio arco hasta sentir un estiramiento en el pecho. Haz una pausa por un momento, luego invierte el movimiento y lleva las mancuernas de nuevo hacia arriba hasta la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0308-yz9nUhF.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0308-yz9nUhF.jpg',
    },
    {
        'name': 'cable cross-over variation',
        'category': 'chest',
        'body_part': 'chest',
        'equipment': 'cable',
        'muscle_group': 'deltoids',
        'target': 'pectorals',
        'secondary_muscles': 'deltoids, triceps',
        'difficulty': 'beginner',
        'instructions': 'Ajusta las poleas del cable a la altura del pecho. Ponte de pie en el centro de la máquina de cable con un pie delante del otro. Sujeta las agarraderas con las palmas hacia abajo y los brazos extendidos hacia los lados. Da un paso hacia adelante, manteniendo los brazos ligeramente flexionados. Con una ligera flexión en los codos, junta las manos frente al pecho. Haz una pausa breve, luego vuelve lentamente los brazos a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0155-0CXGHya.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0155-0CXGHya.jpg',
    },
    {
        'name': 'barbell decline bench press',
        'category': 'chest',
        'body_part': 'chest',
        'equipment': 'barbell',
        'muscle_group': 'triceps',
        'target': 'pectorals',
        'secondary_muscles': 'triceps, shoulders',
        'difficulty': 'beginner',
        'instructions': 'Túmbate en un banco declinado con los pies sujetos y la cabeza más baja que las caderas. Agarra la barra con un agarre pronado un poco más ancho que la separación de los hombros. Saca la barra del soporte y bájala lentamente hacia el pecho, manteniendo los codos pegados al cuerpo. Haz una pausa breve en la parte baja y luego empuja la barra de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0033-GrO65fd.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0033-GrO65fd.jpg',
    },
    {
        'name': 'dumbbell bench press',
        'category': 'chest',
        'body_part': 'chest',
        'equipment': 'dumbbell',
        'muscle_group': 'triceps',
        'target': 'pectorals',
        'secondary_muscles': 'triceps, shoulders',
        'difficulty': 'beginner',
        'instructions': 'Túmbate sobre un banco con los pies apoyados en el suelo y la espalda presionada contra el banco. Sujeta una mancuerna en cada mano, con las palmas hacia adelante y los brazos extendidos por encima del pecho. Baja lentamente las mancuernas hacia los lados del pecho, manteniendo los codos en un ángulo de 90 grados. Haz una pausa breve, luego empuja las mancuernas de vuelta hacia arriba hasta la posición inicial, extendiendo completamente los brazos. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0289-SpYC0Kp.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0289-SpYC0Kp.jpg',
    },
    {
        'name': 'chest dip',
        'category': 'chest',
        'body_part': 'chest',
        'equipment': 'body weight',
        'muscle_group': 'triceps',
        'target': 'pectorals',
        'secondary_muscles': 'triceps, shoulders',
        'difficulty': 'beginner',
        'instructions': 'Colócate en las barras paralelas con los brazos completamente extendidos y el cuerpo recto. Baja el cuerpo flexionando los codos hasta que los hombros queden por debajo de los codos. Empújate de vuelta hacia arriba a la posición inicial extendiendo los brazos. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0251-9WTm7dq.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0251-9WTm7dq.jpg',
    },
    {
        'name': 'barbell deadlift',
        'category': 'upper legs',
        'body_part': 'upper legs',
        'equipment': 'barbell',
        'muscle_group': 'hamstrings',
        'target': 'glutes',
        'secondary_muscles': 'hamstrings, lower back',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros y la barra en el suelo frente a ti. Flexiona las rodillas y las caderas para bajar el torso y agarra la barra con un agarre pronado, con las manos un poco más separadas que el ancho de los hombros. Mantén la espalda recta y el pecho elevado mientras empujas con los talones para levantar la barra del suelo, extendiendo las caderas y las rodillas. Al ponerte de pie, aprieta los glúteos y mantén el core activado. Baja la barra de vuelta al suelo flexionando las caderas y las rodillas, manteniendo la espalda recta. Repite el número de repeticiones deseado.',
        'tips': 'La barra debe rozar las piernas durante todo el movimiento. Activa el dorsal para mantener la espalda recta. Mirada al frente, nunca hacia abajo. Aprieta los glúteos arriba y haz una pausa.',
        'common_mistakes': 'No redondees la espalda baja (riesgo de lesión). No dejes que la barra se aleje del cuerpo. No hiperextiendas la espalda arriba. No dobles excesivamente las rodillas al inicio.',
        'modifications': 'Si tienes problemas de espalda baja, usa sumo deadlift o trap bar. Para principiantes, empieza con peso muerto rumano (desde la barra).',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0032-ila4NZS.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0032-ila4NZS.jpg',
    },
    {
        'name': 'pull-up',
        'category': 'back',
        'body_part': 'back',
        'equipment': 'body weight',
        'muscle_group': 'biceps',
        'target': 'lats',
        'secondary_muscles': 'biceps, forearms',
        'difficulty': 'beginner',
        'instructions': 'Cuélgate de una barra de dominadas con las palmas hacia afuera y los brazos completamente extendidos. Activa el core y junta los omóplatos. Tira de tu cuerpo hacia la barra flexionando los codos y llevando el pecho hacia la barra. Haz una pausa en la parte alta del movimiento y luego baja lentamente el cuerpo de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0652-lBDjFxJ.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0652-lBDjFxJ.jpg',
    },
    {
        'name': 'barbell bent over row',
        'category': 'back',
        'body_part': 'back',
        'equipment': 'barbell',
        'muscle_group': 'biceps',
        'target': 'upper back',
        'secondary_muscles': 'biceps, forearms',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros y las rodillas ligeramente flexionadas. Inclínate hacia delante desde las caderas manteniendo la espalda recta y el pecho elevado. Agarra la barra con un agarre pronado, con las manos un poco más separadas que el ancho de los hombros. Tira de la barra hacia la parte inferior del pecho retrayendo los omóplatos y contrayendo los músculos de la espalda. Haz una pausa breve en la parte alta y luego baja lentamente la barra de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0027-eZyBC3j.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0027-eZyBC3j.jpg',
    },
    {
        'name': 'cable lat pulldown full range of motion',
        'category': 'back',
        'body_part': 'back',
        'equipment': 'cable',
        'muscle_group': 'biceps',
        'target': 'lats',
        'secondary_muscles': 'biceps, rhomboids, rear deltoids',
        'difficulty': 'beginner',
        'instructions': 'Siéntate en la máquina de jalón al pecho con las rodillas colocadas debajo de las almohadillas. Sujeta la barra del cable con un agarre prono, un poco más separado que el ancho de los hombros. Inclínate ligeramente hacia atrás y mantén el pecho elevado, conservando un ligero arco en la zona lumbar. Jala la barra hacia la parte superior del pecho, apretando los omóplatos entre sí. Haz una pausa por un momento en la parte baja del movimiento y luego suelta lentamente la barra de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2330-LEprlgG.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/2330-LEprlgG.jpg',
    },
    {
        'name': 'cable seated row',
        'category': 'back',
        'body_part': 'back',
        'equipment': 'cable',
        'muscle_group': 'biceps',
        'target': 'upper back',
        'secondary_muscles': 'biceps, forearms',
        'difficulty': 'beginner',
        'instructions': 'Siéntate en la máquina de remo con cable con los pies planos sobre los apoyapiés y las rodillas ligeramente flexionadas. Sujeta las agarraderas con un agarre prono, manteniendo la espalda recta y los hombros relajados. Jala las agarraderas hacia el cuerpo, apretando los omóplatos entre sí. Haz una pausa por un momento en el punto máximo del movimiento, luego suelta lentamente las agarraderas de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0861-fUBheHs.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0861-fUBheHs.jpg',
    },
    {
        'name': 'lever t bar row',
        'category': 'back',
        'body_part': 'back',
        'equipment': 'leverage machine',
        'muscle_group': 'biceps',
        'target': 'upper back',
        'secondary_muscles': 'biceps, forearms',
        'difficulty': 'beginner',
        'instructions': 'Ajusta la altura del asiento y la posición de la placa para los pies para asegurar una alineación correcta. Siéntate en la máquina con el pecho contra la almohadilla y los pies planos sobre la placa para los pies. Agarra las agarraderas con un agarre prono, un poco más separadas que el ancho de los hombros. Mantén la espalda recta y activa el core. Tira de las asas hacia el torso, juntando los omóplatos. Haz una pausa en el punto de máxima contracción y luego suelta lentamente las asas hasta la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0606-aaXr7ld.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0606-aaXr7ld.jpg',
    },
    {
        'name': 'lever back extension',
        'category': 'back',
        'body_part': 'back',
        'equipment': 'leverage machine',
        'muscle_group': 'glutes',
        'target': 'spine',
        'secondary_muscles': 'glutes, hamstrings',
        'difficulty': 'beginner',
        'instructions': 'Ajusta la máquina según el tamaño de tu cuerpo y tu rango de movimiento. Siéntate en la máquina con la espalda apoyada en la almohadilla y los pies asegurados. Coloca las manos en las asas o en las barras de agarre. Activa el core e inclínate lentamente hacia adelante, permitiendo que la espalda se redondee ligeramente. Haz una pausa breve en la posición baja, sintiendo un estiramiento en la zona lumbar. Usando los músculos de la espalda, levanta lentamente el torso de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0573-rUXfn3R.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0573-rUXfn3R.jpg',
    },
    {
        'name': 'barbell seated overhead press',
        'category': 'shoulders',
        'body_part': 'shoulders',
        'equipment': 'barbell',
        'muscle_group': 'triceps',
        'target': 'delts',
        'secondary_muscles': 'triceps, upper back',
        'difficulty': 'beginner',
        'instructions': 'Siéntate en un banco con la espalda recta y los pies planos sobre el suelo. Sujeta la barra con un agarre pronado, un poco más ancho que la separación de los hombros. Levanta la barra del soporte y llévala a la altura de los hombros, con los codos flexionados y las palmas hacia delante. Empuja la barra por encima de la cabeza extendiendo completamente los brazos. Haz una pausa breve en la parte alta y luego baja lentamente la barra de vuelta a la altura de los hombros. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0091-kTbSH9h.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0091-kTbSH9h.jpg',
    },
    {
        'name': 'dumbbell lateral raise',
        'category': 'shoulders',
        'body_part': 'shoulders',
        'equipment': 'dumbbell',
        'muscle_group': 'traps',
        'target': 'delts',
        'secondary_muscles': 'traps',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros y sostén una mancuerna en cada mano, con las palmas hacia el cuerpo. Mantén la espalda recta y activa el core. Levanta los brazos hacia los lados hasta que queden paralelos al suelo, manteniendo una ligera flexión en los codos. Haz una pausa por un momento en la parte superior, luego baja lentamente los brazos de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0334-DsgkuIt.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0334-DsgkuIt.jpg',
    },
    {
        'name': 'dumbbell front raise',
        'category': 'shoulders',
        'body_part': 'shoulders',
        'equipment': 'dumbbell',
        'muscle_group': 'biceps',
        'target': 'delts',
        'secondary_muscles': 'biceps, trapezius',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros, sosteniendo una mancuerna en cada mano con las palmas hacia los muslos. Manteniendo los brazos rectos, exhala y levanta las mancuernas frente a ti hasta que queden a la altura de los hombros. Haz una pausa por un momento en la parte superior, luego inhala y baja lentamente las mancuernas de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0310-3eGE2JC.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0310-3eGE2JC.jpg',
    },
    {
        'name': 'dumbbell reverse fly',
        'category': 'shoulders',
        'body_part': 'shoulders',
        'equipment': 'dumbbell',
        'muscle_group': 'trapezius',
        'target': 'delts',
        'secondary_muscles': 'trapezius, rhomboids',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros y sostén una mancuerna en cada mano. Flexiona ligeramente las rodillas e inclínate hacia adelante desde las caderas, manteniendo la espalda recta. Extiende los brazos rectos hacia adelante, con las palmas mirándose entre sí. Manteniendo una ligera flexión en los codos, levanta los brazos hacia los lados hasta que queden paralelos al suelo. Haz una pausa por un momento en la parte superior, luego baja lentamente los brazos de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0383-EAs3xL9.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0383-EAs3xL9.jpg',
    },
    {
        'name': 'dumbbell arnold press',
        'category': 'shoulders',
        'body_part': 'shoulders',
        'equipment': 'dumbbell',
        'muscle_group': 'triceps',
        'target': 'delts',
        'secondary_muscles': 'triceps, upper chest',
        'difficulty': 'beginner',
        'instructions': 'Siéntate en un banco con respaldo y sujeta una mancuerna en cada mano a la altura del hombro, con las palmas hacia tu cuerpo y los codos flexionados. Empuja las mancuernas hacia arriba hasta que los brazos estén completamente extendidos y las palmas miren hacia adelante. Rota las muñecas mientras levantas, de modo que las palmas miren hacia adelante en la parte alta del movimiento. Haz una pausa breve en la parte alta, luego baja lentamente las mancuernas de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2137-Xy4jlWA.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/2137-Xy4jlWA.jpg',
    },
    {
        'name': 'barbell upright row',
        'category': 'shoulders',
        'body_part': 'shoulders',
        'equipment': 'barbell',
        'muscle_group': 'traps',
        'target': 'delts',
        'secondary_muscles': 'traps, biceps',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros y sujeta una barra con agarre prono, manos un poco más separadas que el ancho de los hombros. Deja que la barra cuelgue frente a los muslos, con los brazos completamente extendidos. Manteniendo la espalda recta y el core activado, exhala y levanta la barra en línea recta hacia la barbilla, guiando el movimiento con los codos. Haz una pausa breve en la parte más alta, luego inhala y baja lentamente la barra de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0120-UDlhcO8.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0120-UDlhcO8.jpg',
    },
    {
        'name': 'barbell shrug',
        'category': 'back',
        'body_part': 'back',
        'equipment': 'barbell',
        'muscle_group': 'shoulders',
        'target': 'traps',
        'secondary_muscles': 'shoulders',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros y sujeta una barra frente a ti con un agarre pronado. Mantén los brazos rectos y la espalda recta durante todo el ejercicio. Levanta los hombros hacia las orejas lo más alto posible, apretando los trapecios en la parte alta. Mantén la posición por un momento y luego baja lentamente los hombros de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0095-dG7tG5y.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0095-dG7tG5y.jpg',
    },
    {
        'name': 'barbell curl',
        'category': 'upper arms',
        'body_part': 'upper arms',
        'equipment': 'barbell',
        'muscle_group': 'forearms',
        'target': 'biceps',
        'secondary_muscles': 'forearms',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros y sujeta una barra con un agarre supino, con las palmas mirando hacia delante. Mantén los codos cerca del torso y exhala mientras levantas el peso contrayendo los bíceps. Continúa levantando la barra hasta que los bíceps estén completamente contraídos y la barra esté a la altura de los hombros. Mantén la posición contraída durante una breve pausa mientras aprietas los bíceps. Inhala mientras comienzas a bajar lentamente la barra de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0031-25GPyDY.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0031-25GPyDY.jpg',
    },
    {
        'name': 'dumbbell biceps curl',
        'category': 'upper arms',
        'body_part': 'upper arms',
        'equipment': 'dumbbell',
        'muscle_group': 'forearms',
        'target': 'biceps',
        'secondary_muscles': 'forearms',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con una mancuerna en cada mano, con las palmas hacia adelante y los brazos completamente extendidos. Manteniendo los brazos superiores fijos, exhala y levanta el peso mientras contraes los bíceps. Continúa levantando las pesas hasta que los bíceps estén completamente contraídos y las mancuernas estén a la altura de los hombros. Mantén la posición contraída durante una breve pausa mientras aprietas los bíceps. Inhala y comienza a bajar lentamente las mancuernas de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0294-NbVPDMW.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0294-NbVPDMW.jpg',
    },
    {
        'name': 'dumbbell hammer curl',
        'category': 'upper arms',
        'body_part': 'upper arms',
        'equipment': 'dumbbell',
        'muscle_group': 'forearms',
        'target': 'biceps',
        'secondary_muscles': 'forearms',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con una mancuerna en cada mano, con las palmas mirando hacia el torso. Mantén los codos cerca del torso y gira las palmas de las manos hasta que queden mirando hacia adelante. Esta será tu posición inicial. Ahora, manteniendo los brazos superiores quietos, exhala y flexiona los brazos contrayendo los bíceps. Continúa levantando las pesas hasta que los bíceps estén completamente contraídos y las mancuernas estén a la altura de los hombros. Mantén la posición contraída durante una breve pausa mientras aprietas los bíceps. Luego, inhala y comienza a bajar lentamente las mancuernas de vuelta a la posición inicial. Repite el número de repeticiones recomendado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0313-slDvUAU.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0313-slDvUAU.jpg',
    },
    {
        'name': 'lever preacher curl',
        'category': 'upper arms',
        'body_part': 'upper arms',
        'equipment': 'leverage machine',
        'muscle_group': 'forearms',
        'target': 'biceps',
        'secondary_muscles': 'forearms',
        'difficulty': 'beginner',
        'instructions': 'Ajusta la altura del asiento y colócate en la máquina de palanca. Coloca los brazos superiores en la almohadilla y sujeta las asas con un agarre supino. Mantén la espalda recta y los codos colocados sobre la almohadilla. Exhala y flexiona los antebrazos hacia los brazos superiores, contrayendo los bíceps. Haz una pausa breve en la parte más alta del movimiento, contrayendo los bíceps. Inhala y baja lentamente las asas de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0592-b6hQYMb.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0592-b6hQYMb.jpg',
    },
    {
        'name': 'cable concentration curl',
        'category': 'upper arms',
        'body_part': 'upper arms',
        'equipment': 'cable',
        'muscle_group': 'forearms',
        'target': 'biceps',
        'secondary_muscles': 'forearms',
        'difficulty': 'beginner',
        'instructions': 'Siéntate en un banco o silla con los pies planos en el suelo y las rodillas ligeramente flexionadas. Sujeta la agarradera del cable con agarre supino y apoya el codo en la parte interna del muslo. Manteniendo el brazo superior quieto, exhala y flexiona la agarradera del cable hacia el hombro contrayendo el bíceps. Haz una pausa breve en la parte más alta del movimiento, luego inhala y baja lentamente la agarradera del cable de vuelta a la posición inicial. Repite el número de repeticiones deseado, luego cambia de brazo.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1631-NvfE43H.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/1631-NvfE43H.jpg',
    },
    {
        'name': 'cable curl',
        'category': 'upper arms',
        'body_part': 'upper arms',
        'equipment': 'cable',
        'muscle_group': 'forearms',
        'target': 'biceps',
        'secondary_muscles': 'forearms',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie frente a la máquina de cable con los pies separados a la altura de los hombros. Sujeta el accesorio del cable con agarre supino, palmas hacia arriba. Mantén los codos cerca de los costados y los brazos superiores quietos. Exhala y flexiona el accesorio del cable hacia los hombros, contrayendo los bíceps. Haz una pausa breve en la parte más alta del movimiento, contrayendo los bíceps. Inhala y baja lentamente el accesorio del cable de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0868-G08RZcQ.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0868-G08RZcQ.jpg',
    },
    {
        'name': 'cable pushdown',
        'category': 'upper arms',
        'body_part': 'upper arms',
        'equipment': 'cable',
        'muscle_group': 'forearms',
        'target': 'triceps',
        'secondary_muscles': 'forearms',
        'difficulty': 'beginner',
        'instructions': 'Sujeta una barra recta a una máquina de cable con polea alta. Ponte de pie frente a la máquina con los pies separados a la altura de los hombros y una ligera flexión en las rodillas. Sujeta la barra con un agarre prono, con las manos separadas a la altura de los hombros. Mantén los codos cerca de los costados y los brazos superiores quietos. Exhala y empuja la barra hacia abajo hasta que los codos queden completamente extendidos. Haz una pausa por un momento, luego inhala y regresa lentamente la barra a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0201-3ZflifB.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0201-3ZflifB.jpg',
    },
    {
        'name': 'barbell lying triceps extension skull crusher',
        'category': 'upper arms',
        'body_part': 'upper arms',
        'equipment': 'barbell',
        'muscle_group': 'shoulders',
        'target': 'triceps',
        'secondary_muscles': 'shoulders',
        'difficulty': 'beginner',
        'instructions': 'Túmbate boca arriba en un banco con los pies planos sobre el suelo y la cabeza en el extremo del banco. Sujeta una barra con un agarre pronado, manos separadas a la altura de los hombros, y extiende los brazos rectos por encima del pecho. Manteniendo los brazos superiores fijos, baja lentamente la barra hacia la frente flexionando los codos. Haz una pausa breve cuando la barra esté justo encima de la frente y luego extiende los brazos de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0060-h8LFzo9.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0060-h8LFzo9.jpg',
    },
    {
        'name': 'barbell standing overhead triceps extension',
        'category': 'upper arms',
        'body_part': 'upper arms',
        'equipment': 'barbell',
        'muscle_group': 'shoulders',
        'target': 'triceps',
        'secondary_muscles': 'shoulders',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros y sujeta una barra con agarre prono. Levanta la barra por encima de la cabeza, extendiendo completamente los brazos. Manteniendo los brazos superiores cerca de la cabeza, baja lentamente la barra detrás de la cabeza flexionando los codos. Haz una pausa breve, luego levanta la barra de vuelta a la posición inicial extendiendo los brazos. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0109-dZl9Q27.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0109-dZl9Q27.jpg',
    },
    {
        'name': 'smith close-grip bench press',
        'category': 'upper arms',
        'body_part': 'upper arms',
        'equipment': 'smith machine',
        'muscle_group': 'chest',
        'target': 'triceps',
        'secondary_muscles': 'chest, shoulders',
        'difficulty': 'beginner',
        'instructions': 'Ajusta la altura del asiento y colócate en el banco con los pies planos sobre el suelo. Agarra la barra con un agarre cerrado, un poco más estrecho que el ancho de los hombros. Baja la barra hacia el pecho, manteniendo los codos pegados cerca del cuerpo. Haz una pausa breve en la parte baja y luego empuja la barra de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0751-WcHl7ru.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0751-WcHl7ru.jpg',
    },
    {
        'name': 'three bench dip',
        'category': 'upper arms',
        'body_part': 'upper arms',
        'equipment': 'body weight',
        'muscle_group': 'chest',
        'target': 'triceps',
        'secondary_muscles': 'chest, shoulders',
        'difficulty': 'beginner',
        'instructions': 'Siéntate en un banco con las manos agarrando el borde, los dedos apuntando hacia adelante. Desliza los glúteos fuera del banco, sosteniendo tu peso con las manos. Flexiona los codos y baja el cuerpo hasta que la parte superior de los brazos quede paralela al suelo. Empújate de vuelta hacia arriba hasta la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1753-DQ0cqkT.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/1753-DQ0cqkT.jpg',
    },
    {
        'name': 'barbell squat (on knees)',
        'category': 'upper legs',
        'body_part': 'upper legs',
        'equipment': 'barbell',
        'muscle_group': 'glutes',
        'target': 'quads',
        'secondary_muscles': 'glutes, hamstrings, calves',
        'difficulty': 'beginner',
        'instructions': 'Comienza arrodillado en el suelo con las rodillas separadas a la altura de las caderas y las puntas de los pies apuntando hacia adelante. Coloca una barra sobre los hombros, sujetándola con agarre prono y las manos un poco más separadas que el ancho de los hombros. Activa el core y mantén el pecho elevado mientras bajas lentamente el cuerpo flexionando las rodillas, manteniendo la espalda recta. Continúa bajando hasta que los muslos queden paralelos al suelo, o tan abajo como puedas hacerlo cómodamente. Haz una pausa por un momento en la parte inferior, luego empuja con los talones para regresar a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0102-oR7O9LW.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0102-oR7O9LW.jpg',
    },
    {
        'name': 'barbell front squat',
        'category': 'upper legs',
        'body_part': 'upper legs',
        'equipment': 'barbell',
        'muscle_group': 'quadriceps',
        'target': 'glutes',
        'secondary_muscles': 'quadriceps, hamstrings, calves, core',
        'difficulty': 'beginner',
        'instructions': 'Empieza de pie con los pies separados a la altura de los hombros, con los dedos de los pies ligeramente hacia afuera. Sujeta la barra frente a los hombros, apoyándola sobre la clavícula y los hombros. Activa el core y mantén el pecho elevado mientras bajas el cuerpo hacia una posición de sentadilla, empujando las caderas hacia atrás y flexionando las rodillas. Baja hasta que los muslos queden paralelos al suelo, o tan abajo como puedas hacerlo cómodamente. Haz una pausa por un momento en la parte inferior, luego empuja con los talones para regresar a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0042-zG0zs85.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0042-zG0zs85.jpg',
    },
    {
        'name': 'smith leg press',
        'category': 'upper legs',
        'body_part': 'upper legs',
        'equipment': 'smith machine',
        'muscle_group': 'quadriceps',
        'target': 'glutes',
        'secondary_muscles': 'quadriceps, hamstrings, calves',
        'difficulty': 'beginner',
        'instructions': 'Ajusta el asiento y la placa para los pies de la máquina Smith a una posición cómoda. Siéntate en la máquina con la espalda apoyada en el respaldo y los pies separados a la altura de los hombros sobre la placa para los pies. Sujeta las asas o los lados de la máquina para mayor estabilidad. Empuja la placa alejándola de ti extendiendo las piernas, manteniendo la espalda contra el respaldo. Haz una pausa por un momento en la posición completamente extendida. Dobla lentamente las rodillas y baja la placa de vuelta hacia ti, regresando a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0760-7zdxRTl.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0760-7zdxRTl.jpg',
    },
    {
        'name': 'dumbbell lunge',
        'category': 'upper legs',
        'body_part': 'upper legs',
        'equipment': 'dumbbell',
        'muscle_group': 'quadriceps',
        'target': 'glutes',
        'secondary_muscles': 'quadriceps, hamstrings, calves',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros, sujetando una mancuerna en cada mano. Da un paso adelante con el pie derecho, bajando el cuerpo hasta una posición de zancada. Mantén la espalda recta y el pecho erguido mientras bajas el cuerpo. Empuja con el talón derecho para regresar a la posición inicial. Repite con la pierna izquierda. Alterna las piernas el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0336-RRWFUcw.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0336-RRWFUcw.jpg',
    },
    {
        'name': 'lever leg extension',
        'category': 'upper legs',
        'body_part': 'upper legs',
        'equipment': 'leverage machine',
        'muscle_group': 'hamstrings',
        'target': 'quads',
        'secondary_muscles': 'hamstrings',
        'difficulty': 'beginner',
        'instructions': 'Ajusta la altura del asiento y el respaldo de la máquina a tu cuerpo. Siéntate en la máquina con la espalda apoyada en el respaldo y los pies sobre la almohadilla para los pies. Sujeta las asas o las barras laterales para mayor estabilidad. Extiende las piernas hacia adelante enderezando las rodillas, levantando el peso. Haz una pausa breve en lo alto, luego baja lentamente el peso de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0585-my33uHU.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0585-my33uHU.jpg',
    },
    {
        'name': 'lever lying leg curl',
        'category': 'upper legs',
        'body_part': 'upper legs',
        'equipment': 'leverage machine',
        'muscle_group': 'calves',
        'target': 'hamstrings',
        'secondary_muscles': 'calves',
        'difficulty': 'beginner',
        'instructions': 'Ajusta la máquina a tu cuerpo y selecciona el peso deseado. Túmbate boca abajo en la máquina con las piernas rectas y los talones contra la palanca acolchada. Sujeta las asas o los lados de la máquina para mayor estabilidad. Manteniendo la parte superior del cuerpo inmóvil, exhala y flexiona las piernas hacia arriba tanto como sea posible sin levantar las caderas de la almohadilla. Mantén la posición contraída durante una pausa breve mientras aprietas los isquiotibiales. Inhala y baja lentamente la palanca de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0586-17lJ1kr.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0586-17lJ1kr.jpg',
    },
    {
        'name': 'barbell standing calf raise',
        'category': 'lower legs',
        'body_part': 'lower legs',
        'equipment': 'barbell',
        'muscle_group': 'hamstrings',
        'target': 'calves',
        'secondary_muscles': 'hamstrings, glutes',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros y coloca una barra sobre la parte superior de la espalda. Levanta los talones del suelo lo más alto posible, apoyándote solo en las puntas de los pies. Haz una pausa breve en la parte alta y luego baja lentamente los talones de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1372-8ozhUIZ.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/1372-8ozhUIZ.jpg',
    },
    {
        'name': 'barbell romanian deadlift',
        'category': 'upper legs',
        'body_part': 'upper legs',
        'equipment': 'barbell',
        'muscle_group': 'hamstrings',
        'target': 'glutes',
        'secondary_muscles': 'hamstrings, lower back',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros y los dedos de los pies apuntando hacia delante. Sujeta la barra con un agarre pronado, manos un poco más separadas que el ancho de los hombros. Flexiona las caderas, manteniendo la espalda recta y las rodillas ligeramente flexionadas. Baja la barra hacia el suelo, manteniéndola cerca del cuerpo. Siente el estiramiento en los isquiotibiales mientras bajas la barra. Cuando sientas el estiramiento en los isquiotibiales, empuja las caderas hacia delante y ponte de pie. Aprieta los glúteos en la parte alta del movimiento. Baja la barra de vuelta a la posición inicial y repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0085-wQ2c4XD.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0085-wQ2c4XD.jpg',
    },
    {
        'name': 'dumbbell goblet squat',
        'category': 'upper legs',
        'body_part': 'upper legs',
        'equipment': 'dumbbell',
        'muscle_group': 'glutes',
        'target': 'quads',
        'secondary_muscles': 'glutes, hamstrings, calves',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros, sosteniendo una mancuerna verticalmente contra el pecho con ambas manos. Manteniendo el pecho erguido y el core activado, baja el cuerpo a una posición de sentadilla empujando las caderas hacia atrás y flexionando las rodillas. Continúa bajando hasta que los muslos queden paralelos al suelo, o tan abajo como puedas hacerlo cómodamente. Haz una pausa por un momento en la parte inferior, luego empuja con los talones para regresar a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1760-yn8yg1r.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/1760-yn8yg1r.jpg',
    },
    {
        'name': 'barbell glute bridge',
        'category': 'upper legs',
        'body_part': 'upper legs',
        'equipment': 'barbell',
        'muscle_group': 'hamstrings',
        'target': 'glutes',
        'secondary_muscles': 'hamstrings, lower back',
        'difficulty': 'beginner',
        'instructions': 'Empieza tumbado boca arriba en el suelo con las rodillas flexionadas y los pies planos sobre el suelo. Coloca una barra sobre las caderas, sujetándola con firmeza con ambas manos. Activa los glúteos y el core, luego levanta las caderas del suelo hasta que el cuerpo forme una línea recta desde las rodillas hasta los hombros. Haz una pausa breve en la parte alta, apretando los glúteos. Baja lentamente las caderas de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1409-qKBpF7I.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/1409-qKBpF7I.jpg',
    },
    {
        'name': 'cable kickback',
        'category': 'upper arms',
        'body_part': 'upper arms',
        'equipment': 'cable',
        'muscle_group': 'shoulders',
        'target': 'triceps',
        'secondary_muscles': 'shoulders',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie frente a una máquina de cable con los pies separados a la altura de los hombros. Sujeta la agarradera del cable con la mano derecha y retrocede un paso para crear tensión en el cable. Flexiona ligeramente las rodillas e inclínate hacia adelante desde las caderas, manteniendo la espalda recta. Mantén la parte superior del brazo cerca del cuerpo y el codo flexionado en un ángulo de 90 grados. Extiende el antebrazo hacia atrás, enderezando el brazo por completo. Haz una pausa por un momento, luego regresa lentamente a la posición inicial. Repite el número de repeticiones deseado, luego cambia de lado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0860-HEJ6DIX.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0860-HEJ6DIX.jpg',
    },
    {
        'name': 'front plank with twist',
        'category': 'waist',
        'body_part': 'waist',
        'equipment': 'body weight',
        'muscle_group': 'obliques',
        'target': 'abs',
        'secondary_muscles': 'obliques, shoulders',
        'difficulty': 'beginner',
        'instructions': 'Comienza en posición de plancha alta con las manos directamente debajo de los hombros y el cuerpo en línea recta de la cabeza a los pies. Activa el core y los glúteos para mantener una posición estable. Gira el torso hacia la derecha, levantando el brazo derecho y extendiéndolo hacia el techo. Mantén las caderas y las piernas estables mientras giras. Mantén la posición por un momento, luego regresa a la posición inicial. Repite el giro hacia el lado izquierdo. Continúa alternando lados durante el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0464-CosupLu.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0464-CosupLu.jpg',
    },
    {
        'name': 'tuck crunch',
        'category': 'waist',
        'body_part': 'waist',
        'equipment': 'body weight',
        'muscle_group': 'hip flexors',
        'target': 'abs',
        'secondary_muscles': 'hip flexors',
        'difficulty': 'beginner',
        'instructions': 'Túmbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. Coloca las manos detrás de la cabeza con los codos apuntando hacia afuera. Activando el abdomen, levanta los omóplatos del suelo y lleva las rodillas hacia el pecho, curvando al mismo tiempo la parte superior del cuerpo hacia las rodillas. Haz una pausa de un momento en la parte superior, luego baja lentamente los omóplatos y extiende las piernas de nuevo a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0871-BMMolZ3.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0871-BMMolZ3.jpg',
    },
    {
        'name': '3/4 sit-up',
        'category': 'waist',
        'body_part': 'waist',
        'equipment': 'body weight',
        'muscle_group': 'hip flexors',
        'target': 'abs',
        'secondary_muscles': 'hip flexors, lower back',
        'difficulty': 'beginner',
        'instructions': 'Túmbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. Coloca las manos detrás de la cabeza con los codos apuntando hacia afuera. Activando el abdomen, levanta lentamente la parte superior del cuerpo del suelo, curvándote hacia adelante hasta que tu torso forme un ángulo de 45 grados. Haz una pausa por un momento en la parte superior, luego baja lentamente la parte superior del cuerpo de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0001-2gPfomN.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0001-2gPfomN.jpg',
    },
    {
        'name': 'hanging leg raise',
        'category': 'waist',
        'body_part': 'waist',
        'equipment': 'body weight',
        'muscle_group': 'hip flexors',
        'target': 'abs',
        'secondary_muscles': 'hip flexors',
        'difficulty': 'beginner',
        'instructions': 'Cuélgate de una barra de dominadas con los brazos completamente extendidos y las palmas mirando hacia afuera. Activa el core y levanta las piernas frente a ti, manteniéndolas rectas. Continúa levantando hasta que las piernas estén paralelas al suelo o tan alto como puedas llegar cómodamente. Haz una pausa por un momento en la parte superior, luego baja lentamente las piernas de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0472-I3tsCnC.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0472-I3tsCnC.jpg',
    },
    {
        'name': 'russian twist',
        'category': 'waist',
        'body_part': 'waist',
        'equipment': 'body weight',
        'muscle_group': 'obliques',
        'target': 'abs',
        'secondary_muscles': 'obliques',
        'difficulty': 'beginner',
        'instructions': 'Siéntate en el suelo con las rodillas flexionadas y los pies apoyados en el suelo. Inclínate ligeramente hacia atrás manteniendo la espalda recta y el core activado. Junta las manos frente al pecho o sujeta una pesa si lo deseas. Levanta los pies del suelo, equilibrándote sobre los isquiones. Gira el torso hacia la derecha, llevando las manos o la pesa hacia el lado derecho del cuerpo. Haz una pausa por un momento, luego gira el torso hacia la izquierda, llevando las manos o la pesa hacia el lado izquierdo del cuerpo. Continúa alternando lados durante el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0687-XVDdcoj.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0687-XVDdcoj.jpg',
    },
    {
        'name': 'band bicycle crunch',
        'category': 'waist',
        'body_part': 'waist',
        'equipment': 'band',
        'muscle_group': 'hip flexors',
        'target': 'abs',
        'secondary_muscles': 'hip flexors, obliques',
        'difficulty': 'beginner',
        'instructions': 'Túmbate sobre tu espalda con las manos detrás de la cabeza y las rodillas flexionadas. Levanta los pies del suelo y lleva la rodilla derecha hacia el pecho mientras simultáneamente giras el torso para llevar el codo izquierdo hacia la rodilla derecha. Estira la pierna derecha mientras llevas la rodilla izquierda hacia el pecho y giras el torso para llevar el codo derecho hacia la rodilla izquierda. Continúa alternando el movimiento de giro, como si estuvieras pedaleando una bicicleta, manteniendo el core activado durante todo el movimiento. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0972-tZkGYZ9.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0972-tZkGYZ9.jpg',
    },
    {
        'name': 'mountain climber',
        'category': 'cardio',
        'body_part': 'cardio',
        'equipment': 'body weight',
        'muscle_group': 'core',
        'target': 'cardiovascular system',
        'secondary_muscles': 'core, shoulders, triceps',
        'difficulty': 'beginner',
        'instructions': 'Comienza en una posición de plancha alta con las manos justo debajo de los hombros y el cuerpo en línea recta. Activa el core y lleva la rodilla derecha hacia el pecho, luego cambia rápidamente y lleva la rodilla izquierda hacia el pecho. Continúa alternando las piernas con un movimiento de carrera, manteniendo las caderas bajas y el core activado. Mantén un ritmo constante y respira de forma regular durante todo el ejercicio. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0630-RJgzwny.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/0630-RJgzwny.jpg',
    },
    {
        'name': 'captains chair straight leg raise',
        'category': 'waist',
        'body_part': 'waist',
        'equipment': 'body weight',
        'muscle_group': 'hip flexors',
        'target': 'abs',
        'secondary_muscles': 'hip flexors',
        'difficulty': 'beginner',
        'instructions': 'Siéntate en la silla romana con la espalda apoyada en el respaldo y los antebrazos apoyados en las almohadillas. Mantén la parte superior del cuerpo estable y la espalda recta. Activa el abdomen y levanta las piernas frente a ti, manteniéndolas rectas. Continúa levantando hasta que las piernas estén paralelas al suelo o tan alto como puedas llegar cómodamente. Haz una pausa por un momento en la parte superior, luego baja lentamente las piernas de vuelta a la posición inicial. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2963-weoDEpH.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/2963-weoDEpH.jpg',
    },
    {
        'name': 'burpee',
        'category': 'cardio',
        'body_part': 'cardio',
        'equipment': 'body weight',
        'muscle_group': 'quadriceps',
        'target': 'cardiovascular system',
        'secondary_muscles': 'quadriceps, hamstrings, calves, shoulders, chest',
        'difficulty': 'beginner',
        'instructions': 'Comienza de pie con los pies separados a la altura de los hombros. Baja el cuerpo hacia una posición de sentadilla flexionando las rodillas y colocando las manos en el suelo frente a ti. Lleva los pies hacia atrás de una patada hasta una posición de flexión de brazos. Realiza una flexión de brazos, manteniendo el cuerpo en línea recta. Salta con los pies de vuelta a la posición de sentadilla. Salta hacia arriba explosivamente, llevando los brazos por encima de la cabeza. Aterriza suavemente y baja de inmediato a una posición de sentadilla para comenzar la siguiente repetición.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1160-dK9394r.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/1160-dK9394r.jpg',
    },
    {
        'name': 'high knee against wall',
        'category': 'cardio',
        'body_part': 'cardio',
        'equipment': 'body weight',
        'muscle_group': 'quadriceps',
        'target': 'cardiovascular system',
        'secondary_muscles': 'quadriceps, hamstrings, glutes, calves',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie frente a una pared con los pies separados a la altura de las caderas. Coloca las manos en la pared para mayor apoyo. Activa el core y levanta la rodilla derecha hacia el pecho, mientras mantienes el pie izquierdo en el suelo. Cambia rápidamente de pierna, llevando la rodilla izquierda hacia el pecho y bajando el pie derecho de nuevo. Continúa alternando las piernas con un movimiento de carrera, llevando las rodillas lo más alto posible. Mantén un ritmo rápido y la parte superior del cuerpo estable durante todo el ejercicio. Repite durante la duración o el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/3636-ealLwvX.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/3636-ealLwvX.jpg',
    },
    {
        'name': 'astride jumps (male)',
        'category': 'cardio',
        'body_part': 'cardio',
        'equipment': 'body weight',
        'muscle_group': 'quadriceps',
        'target': 'cardiovascular system',
        'secondary_muscles': 'quadriceps, hamstrings, calves',
        'difficulty': 'beginner',
        'instructions': 'Ponte de pie con los pies separados a la altura de los hombros. Flexiona las rodillas y baja el cuerpo hacia una posición de sentadilla. Salta explosivamente hacia arriba, extendiendo las piernas y los brazos. Mientras estás en el aire, separa las piernas y lleva los brazos hacia los lados. Aterriza suavemente con los pies separados a la altura de los hombros, flexionando las rodillas para absorber el impacto. Repite el número de repeticiones deseado.',
        'gif_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/3220-f9lVSSI.gif',
        'image_url': 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/images/3220-f9lVSSI.jpg',
    },
]
