"""Add security middleware and rate limiting

Revision ID: 9b95a5f6c046
Revises: f07040f8de07
Create Date: 2026-02-04 13:09:24.910818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b95a5f6c046'
down_revision: Union[str, Sequence[str], None] = 'f07040f8de07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
