"""Separate user and client models with proper relationships

Revision ID: a49ef42046dc
Revises: 9b95a5f6c046
Create Date: 2026-02-04 14:35:04.347309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a49ef42046dc'
down_revision: Union[str, Sequence[str], None] = '9b95a5f6c046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('membership_type', sa.String(length=20), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)

    # Handle attendance table
    op.add_column('attendance', sa.Column('client_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('attendance_ibfk_1'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'clients', ['client_id'], ['id'])
    op.drop_column('attendance', 'user_id')

    # Handle memberships table
    op.add_column('memberships', sa.Column('client_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('memberships_ibfk_1'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'clients', ['client_id'], ['id'])
    op.drop_column('memberships', 'user_id')

    # Handle facial_encodings table - drop FK and unique constraint separately
    op.add_column('facial_encodings', sa.Column('client_id', sa.Integer(), nullable=True))
    # Drop the foreign key constraint first
    op.drop_constraint('facial_encodings_ibfk_1', 'facial_encodings', type_='foreignkey')
    # Drop the unique constraint (which also removes the index)
    op.drop_constraint('user_id', 'facial_encodings', type_='unique')
    # Add the new column and constraints
    op.create_unique_constraint(None, 'facial_encodings', ['client_id'])
    op.create_foreign_key(None, 'facial_encodings', 'clients', ['client_id'], ['id'])
    op.drop_column('facial_encodings', 'user_id')

    # Handle users table
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'membership_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('membership_type', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('profile_image', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'role')
    op.add_column('memberships', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_ibfk_1'), 'memberships', 'users', ['user_id'], ['id'])
    op.drop_column('memberships', 'client_id')
    op.add_column('facial_encodings', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'facial_encodings', type_='foreignkey')
    op.create_foreign_key(op.f('facial_encodings_ibfk_1'), 'facial_encodings', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'facial_encodings', type_='unique')
    op.create_index(op.f('user_id'), 'facial_encodings', ['user_id'], unique=True)
    op.drop_column('facial_encodings', 'client_id')
    op.add_column('attendance', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_ibfk_1'), 'attendance', 'users', ['user_id'], ['id'])
    op.drop_column('attendance', 'client_id')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
